'use client'

import { useEffect, useState } from 'react'
import { googleLoginUrl, getGoogleSites, getGoogleProperties, type GoogleSite, type GoogleProperty } from '../../lib/google-api'

export default function ConnectGoogle() {
  const [ar,setAr]=useState(false); const [sites,setSites]=useState<GoogleSite[]>([]); const [properties,setProperties]=useState<GoogleProperty[]>([]); const [site,setSite]=useState(''); const [property,setProperty]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [connected,setConnected]=useState(false)
  useEffect(()=>{setAr(navigator.language.toLowerCase().startsWith('ar'));void loadGoogle()},[])
  async function loadGoogle(){setLoading(true);setError('');try{const [s,p]=await Promise.all([getGoogleSites(),getGoogleProperties()]);setSites(s);setProperties(p);setConnected(true);const saved=JSON.parse(localStorage.getItem('googleSelection')||'null');const savedSite=saved?.siteUrl||saved?.site;const savedProperty=saved?.property;setSite(savedSite&&s.some(x=>x.siteUrl===savedSite)?savedSite:(s[0]?.siteUrl||''));setProperty(savedProperty&&p.some(x=>x.name===savedProperty)?savedProperty:(p[0]?.name||''))}catch(e){setConnected(false);setError(e instanceof Error?e.message:(ar?'تعذر جلب بيانات Google':'Unable to load Google data'))}finally{setLoading(false)}}
  function analyze(){if(!site||!property){setError(ar?'اختر الموقع وخصائص GA4 أولاً':'Choose a website and GA4 property first');return}localStorage.setItem('googleSelection',JSON.stringify({siteUrl:site,property}));location.href='/dashboard'}
  const t=ar?{brand:'إلديفو تحليلات',title:'ربط Google',desc:'تم تسجيل الدخول. اختر الموقع وخصائص GA4 لتحليل البيانات الحقيقية.',connect:'تسجيل الدخول باستخدام Google',site:'موقع Search Console',prop:'خاصية GA4',choose:'اختر',refresh:'تحديث البيانات',analyze:'بدء التحليل',not:'غير متصل',connected:'Google متصل — بيانات حقيقية',security:'بيانات الاعتماد السرية تبقى على خادم Vercel ولا تظهر في المتصفح.'}:{brand:'ELDEVO ANALYTICS',title:'Connect Google',desc:'You are signed in. Choose a Search Console website and GA4 property for live analysis.',connect:'Sign in with Google',site:'Search Console website',prop:'GA4 property',choose:'Choose',refresh:'Refresh Google data',analyze:'Start analysis',not:'Not connected',connected:'Google connected — live data',security:'Secrets stay on the Vercel server and are never exposed in the browser.'}
  return <main dir={ar?'rtl':'ltr'} style={{minHeight:'100vh',background:'#f6f8fb',padding:'40px 20px',fontFamily:'Inter,system-ui,sans-serif'}}><div style={{maxWidth:940,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'flex-end',marginBottom:12}}><button onClick={()=>setAr(!ar)}>{ar?'English':'العربية'}</button></div><div style={{background:'#fff',border:'1px solid #e5e9f0',borderRadius:18,padding:28}}><div style={{display:'flex',justifyContent:'space-between',gap:20,alignItems:'flex-start'}}><div><div style={{fontSize:14,color:'#635bff',fontWeight:800}}>{t.brand}</div><h1 style={{fontSize:32,margin:'8px 0'}}>{t.title}</h1><p style={{color:'#667085'}}>{t.desc}</p></div><div>{connected?'● '+t.connected:'● '+t.not}</div></div><div style={{marginTop:26,padding:20,borderRadius:14,background:'#f7f7ff'}}><p>{ar?'بعد العودة من Google يتم جلب المواقع والخصائص تلقائيًا.':'Sites and GA4 properties are loaded automatically after Google sign-in.'}</p><a href={googleLoginUrl('/connect')}>{t.connect}</a></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginTop:18}}><label><b>2 — {t.site}</b><select value={site} onChange={e=>setSite(e.target.value)} disabled={!sites.length}><option value="">{t.choose}</option>{sites.map(s=><option key={s.siteUrl} value={s.siteUrl}>{s.siteUrl}</option>)}</select></label><label><b>3 — {t.prop}</b><select value={property} onChange={e=>setProperty(e.target.value)} disabled={!properties.length}><option value="">{t.choose}</option>{properties.map(p=><option key={p.name} value={p.name}>{p.displayName} · {p.name}</option>)}</select></label></div>{error&&<div style={{marginTop:16,color:'#b42318'}}>{error}</div>}{loading&&<div style={{marginTop:16}}>{ar?'جاري جلب البيانات الحقيقية من Google…':'Loading live Google data…'}</div>}<div style={{marginTop:22}}><button onClick={loadGoogle} disabled={loading}>{loading?'…':t.refresh}</button> <button onClick={analyze} disabled={!site||!property}>{t.analyze}</button></div><div style={{marginTop:24,color:'#667085'}}>{t.security}</div></div></div></main>
}
