'use client'

import { useMemo, useState } from 'react'
import { BarChart, Bar, CartesianGrid, LineChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Download, RefreshCw, Search, Sparkles, TrendingUp, Users, MousePointerClick, Eye, Globe2, Smartphone, FileText, Target, Settings, ChevronRight } from 'lucide-react'

const trend = Array.from({length:14}, (_,i)=>({date:`Aug ${i+1}`, clicks:760+i*48+(i%3)*35, impressions:11200+i*720+(i%4)*260, users:980+i*52}))
const queries=[['ai tools',2410,18900,12.8,3.1],['free ai tools',1980,22300,8.9,5.4],['ai finder',1540,9800,15.7,2.6],['best ai tools',920,11200,8.2,6.8],['seo tools',810,14900,5.4,9.2],['ai websites',690,10100,6.8,8.1]]
const pages=[['/',4820,124500,3.87,2.8],['/ai-finder',3410,98240,3.47,4.1],['/tools',2890,86100,3.36,5.2],['/categories',2210,74300,2.97,6.4],['/blog/google-seo',1840,61500,2.99,7.1]]
const countries=[['Türkiye',8420,31.4],['United States',6240,23.3],['Germany',2410,9.0],['United Kingdom',1980,7.4],['France',1320,4.9]]

export default function Dashboard(){
 const [section,setSection]=useState('Overview'); const [range,setRange]=useState('Last 28 days'); const [source,setSource]=useState('Demo'); const [notice,setNotice]=useState('')
 const title=section==='Overview'?'Performance overview':section
 const show=(msg:string)=>{setNotice(msg);setTimeout(()=>setNotice(''),2500)}
 const data=useMemo(()=>trend,[range])
 return <div className="shell">
  <header className="topbar"><div className="brand">Eldevo <span>Analytics</span></div><div className="top-actions"><span className={`status ${source==='Google API'?'live':''}`}>{source==='Google API'?'● Live Google data':'● Demo data'}</span><button className="btn" onClick={()=>show('Sync is ready for the Google API connection.') }><RefreshCw size={15}/> Sync</button><button className="btn primary" onClick={()=>show('Report export is ready for the connected-data flow.') }><Download size={16}/> Export</button></div></header>
  <div className="layout"><aside className="sidebar"><div className="nav-title">Workspace</div>{['Overview','Search Console','Analytics','SEO Opportunities','Reports'].map(x=><button key={x} className={`nav ${section===x?'active':''}`} onClick={()=>setSection(x)}>{x}</button>)}<div className="nav-title" style={{marginTop:25}}>Analysis</div>{['Keywords','Pages','Countries','Devices','Conversions'].map(x=><button key={x} className={`nav ${section===x?'active':''}`} onClick={()=>setSection(x)}>{x}</button>)}<div className="nav-title" style={{marginTop:25}}>Configuration</div><button className={`nav ${section==='Google Connection'?'active':''}`} onClick={()=>setSection('Google Connection')}><Settings size={15}/> Google Connection</button></aside>
  <main className="main"><div className="headline"><div><h1>{title}</h1><div className="muted">eldevo.com · Search Console + GA4 intelligence</div></div><div className="filters"><select className="filter" value={range} onChange={e=>setRange(e.target.value)}><option>Last 7 days</option><option>Last 28 days</option><option>Last 3 months</option><option>Last 6 months</option><option>Last 12 months</option><option>Custom range</option></select><select className="filter" value={source} onChange={e=>setSource(e.target.value)}><option>Demo</option><option>Google API</option></select></div></div>
  {notice&&<div className="notice">{notice}</div>}
  {section==='Overview'?<Overview data={data} onNavigate={setSection}/>:section==='Search Console'?<SearchConsole/>:section==='Analytics'?<Analytics/>:section==='SEO Opportunities'?<Opportunities/>:section==='Keywords'?<DataTable title="Keywords" columns={['Query','Clicks','Impressions','CTR','Position']} rows={queries.map(r=>[r[0],r[1].toLocaleString(),r[2].toLocaleString(),`${r[3]}%`,r[4]])}/>:section==='Pages'?<DataTable title="Pages" columns={['Page','Clicks','Impressions','CTR','Position']} rows={pages.map(r=>[r[0],r[1].toLocaleString(),r[2].toLocaleString(),`${r[3]}%`,r[4]])}/>:section==='Countries'?<DataTable title="Countries" columns={['Country','Clicks','Share']} rows={countries.map(r=>[r[0],r[1].toLocaleString(),`${r[2]}%`])}/>:section==='Devices'?<Devices/>:section==='Conversions'?<Conversions/>:section==='Reports'?<Reports show={show}/>:<GoogleConnection source={source} setSource={setSource}/>}</main></div></div>
}
function Overview({data,onNavigate}:{data:any[];onNavigate:(x:string)=>void}){return <><div className="cards"><Metric icon={<MousePointerClick/>} label="Organic clicks" value="24,850" change="+18.4%"/><Metric icon={<Eye/>} label="Impressions" value="1.24M" change="+12.7%"/><Metric icon={<TrendingUp/>} label="Average position" value="11.8" change="↑ 2.4"/><Metric icon={<Users/>} label="Users" value="38,420" change="+21.0%"/></div><div className="grid"><Panel title="Organic search trend" sub="Clicks, impressions and users"><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="clicks" strokeWidth={3}/><Line type="monotone" dataKey="users" strokeWidth={2}/></LineChart></ResponsiveContainer></div></Panel><Panel title="AI executive summary" sub="Automated interpretation"><Insight title="Growth is accelerating" text="Organic clicks are up 18.4% and the strongest gains come from high-intent AI pages."/><Insight title="12 quick-win keywords" text="Queries ranking between positions 4–10 have meaningful impression volume."/><Insight title="CTR opportunity detected" text="8 pages have high impressions but below-average CTR."/></Panel></div><div className="grid"><Panel title="Top landing pages" sub="Search performance"><DataTable compact columns={['Page','Clicks','Impressions','CTR','Position']} rows={pages.slice(0,4).map(r=>[r[0],r[1].toLocaleString(),r[2].toLocaleString(),`${r[3]}%`,r[4]])}/></Panel><Panel title="Traffic by channel" sub="GA4 acquisition"><div className="chart small"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:'Organic',value:38},{name:'Direct',value:27},{name:'Referral',value:18},{name:'Social',value:11},{name:'Other',value:6}]}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="value"/></BarChart></ResponsiveContainer></div></Panel></div><div className="report"><div><h2><Sparkles size={20}/> Generate intelligence report</h2><p>Full PDF/Excel summary for the selected period, comparisons, charts and recommendations.</p></div><button className="btn" onClick={()=>onNavigate('Reports')}>Create report <ChevronRight size={16}/></button></div></>}
function SearchConsole(){return <><SectionHero icon={<Search/>} title="Google Search Console" text="Real-data placeholders for Search Analytics API: property, queries, pages, countries, devices and dates."/><div className="cards"><Metric icon={<MousePointerClick/>} label="Clicks" value="24,850" change="+18.4%"/><Metric icon={<Eye/>} label="Impressions" value="1.24M" change="+12.7%"/><Metric icon={<Target/>} label="CTR" value="2.01%" change="+0.3%"/><Metric icon={<TrendingUp/>} label="Position" value="11.8" change="↑ 2.4"/></div><Panel title="Search performance" sub="Connect Search Console to replace demo values with API results"><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line dataKey="clicks"/><Line dataKey="impressions"/></LineChart></ResponsiveContainer></div></Panel></>}
function Analytics(){return <><SectionHero icon={<Users/>} title="Google Analytics 4" text="GA4 data areas: acquisition, users, sessions, engagement, events, conversions and landing pages."/><div className="cards"><Metric icon={<Users/>} label="Users" value="38,420" change="+21%"/><Metric icon={<TrendingUp/>} label="Sessions" value="51,230" change="+17%"/><Metric icon={<Target/>} label="Engagement" value="64.2%" change="+4.1%"/><Metric icon={<MousePointerClick/>} label="Key events" value="1,842" change="+28%"/></div><Panel title="Acquisition channels" sub="GA4 Data API placeholder"><DataTable columns={['Channel','Users','Sessions','Engagement','Key events']} rows={[['Organic Search','15,420','21,130','68.4%','842'],['Direct','10,240','13,800','61.2%','410'],['Referral','6,820','8,420','59.8%','280'],['Social','4,210','5,100','52.1%','190']]}/></Panel></>}
function Opportunities(){return <><SectionHero icon={<Sparkles/>} title="SEO Opportunities" text="Actionable findings calculated from Search Console metrics."/><div className="cards"><Metric icon={<Target/>} label="Quick wins" value="12" change="High"/><Metric icon={<TrendingUp/>} label="Rising queries" value="34" change="+18%"/><Metric icon={<Eye/>} label="CTR issues" value="8" change="Review"/><Metric icon={<Search/>} label="Declining queries" value="17" change="Monitor"/></div><DataTable title="Priority opportunities" columns={['Opportunity','Evidence','Potential','Action']} rows={[['Position 4–10 keywords','High impressions','High','Improve content + titles'],['High impressions / low CTR','CTR below site median','High','Rewrite title/meta'],['Declining pages','Clicks down >20%','Medium','Refresh content'],['New rising queries','Fast impression growth','Medium','Create supporting content']]}/></>}
function Devices(){return <><SectionHero icon={<Smartphone/>} title="Devices" text="Search Console device performance and GA4 device categories."/><DataTable columns={['Device','Clicks','Impressions','CTR','Users']} rows={[['Mobile','15,820','782,000','2.02%','25,410'],['Desktop','7,940','382,000','2.08%','10,840'],['Tablet','1,090','76,000','1.43%','2,170']]}/></>}
function Conversions(){return <><SectionHero icon={<Target/>} title="Conversions" text="Key events and conversion performance from GA4."/><div className="cards"><Metric icon={<Target/>} label="Key events" value="1,842" change="+28%"/><Metric icon={<Users/>} label="Converted users" value="1,120" change="+19%"/><Metric icon={<TrendingUp/>} label="Conversion rate" value="2.91%" change="+0.42%"/><Metric icon={<MousePointerClick/>} label="Value" value="$8,420" change="+31%"/></div><DataTable columns={['Event','Count','Users','Rate']} rows={[['generate_lead','620','410','1.07%'],['sign_up','510','460','1.20%'],['contact','382','290','0.75%'],['purchase','330','180','0.47%']]}/></>}
function Reports({show}:{show:(x:string)=>void}){return <><SectionHero icon={<FileText/>} title="Reports" text="Build a complete export for any selected period."/><div className="report-builder"><label>Report name<input placeholder="Monthly SEO & Analytics Report"/></label><label>Property<input placeholder="eldevo.com"/></label><label>From<input type="date"/></label><label>To<input type="date"/></label><label>Include comparison<select><option>Previous period</option><option>Previous year</option><option>None</option></select></label><label>Formats<select><option>PDF + Excel + CSV</option><option>PDF</option><option>Excel</option></select></label><button className="btn primary" onClick={()=>show('Report configuration saved. Real export will use connected Google data.')}>Generate full report</button></div><div className="panel"><h2>Report contents</h2><p>KPIs · charts · Search Console · GA4 · keywords · pages · countries · devices · conversions · comparisons · anomalies · opportunities · AI summary.</p></div></>}
function GoogleConnection({source,setSource}:{source:string;setSource:(x:string)=>void}){return <><SectionHero icon={<Settings/>} title="Google Connection" text="Enter configuration references here. Secrets must never be committed to GitHub Pages."/><div className="connection-grid"><div className="panel"><h2>Search Console</h2><label>Property URL<input placeholder="https://eldevo.com/"/></label><label>Google OAuth Client ID<input placeholder="YOUR_GOOGLE_CLIENT_ID"/></label><label>Redirect URI<input placeholder="https://YOUR-BACKEND/api/auth/google/callback" readOnly/></label></div><div className="panel"><h2>Google Analytics 4</h2><label>Property ID<input placeholder="123456789"/></label><label>Measurement ID<input placeholder="G-XXXXXXXXXX"/></label><label>OAuth status<select value={source} onChange={e=>setSource(e.target.value)}><option>Demo</option><option>Google API</option></select></label></div></div><div className="notice">For real OAuth/API data, use a secure backend. GitHub Pages is static and cannot safely store GOOGLE_CLIENT_SECRET.</div></>}
function SectionHero({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="section-hero"><span>{icon}</span><div><h2>{title}</h2><p>{text}</p></div></div>}
function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="panel"><h2>{title}</h2><p>{sub}</p>{children}</section>}
function Insight({title,text}:{title:string;text:string}){return <div className="insight"><span className="dot"/><div><b>{title}</b><br/><span className="muted">{text}</span></div></div>}
function DataTable({title,columns,rows,compact=false}:{title?:string;columns:string[];rows:any[][];compact?:boolean}){return <section className={compact?'':'panel'}>{title&&<><h2>{title}</h2><p>Demo data — replace with Google API results when connected.</p></>}<div className="table-wrap"><table className="table"><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<b>{c}</b>:c}</td>)}</tr>)}</tbody></table></div></section>}
function Metric({icon,label,value,change}:{icon:React.ReactNode;label:string;value:string;change:string}){return <div className="card"><div className="metric-head"><span className="card-label">{label}</span><span className="metric-icon">{icon}</span></div><div className="metric">{value}</div><span className="up">{change}</span> <span className="muted">vs previous</span></div>}
